# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rss_pb2 as rss__pb2


class RssServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Inspect = channel.unary_unary(
        '/gateway.RssService/Inspect',
        request_serializer=rss__pb2.InspectRequest.SerializeToString,
        response_deserializer=rss__pb2.InspectResponse.FromString,
        )
    self.Reply = channel.unary_unary(
        '/gateway.RssService/Reply',
        request_serializer=rss__pb2.ReplyRequest.SerializeToString,
        response_deserializer=rss__pb2.ReplyResponse.FromString,
        )


class RssServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Inspect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Reply(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RssServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Inspect': grpc.unary_unary_rpc_method_handler(
          servicer.Inspect,
          request_deserializer=rss__pb2.InspectRequest.FromString,
          response_serializer=rss__pb2.InspectResponse.SerializeToString,
      ),
      'Reply': grpc.unary_unary_rpc_method_handler(
          servicer.Reply,
          request_deserializer=rss__pb2.ReplyRequest.FromString,
          response_serializer=rss__pb2.ReplyResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gateway.RssService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
