# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rss.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rss.proto',
  package='gateway',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\trss.proto\x12\x07gateway\"\x1f\n\x0cReplyRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rReplyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0eInspectRequest\x12\x0b\n\x03uri\x18\x01 \x01(\t\"\x1e\n\x0fInspectResponse\x12\x0b\n\x03rss\x18\x01 \x03(\t2\x86\x01\n\nRssService\x12>\n\x07Inspect\x12\x17.gateway.InspectRequest\x1a\x18.gateway.InspectResponse\"\x00\x12\x38\n\x05Reply\x12\x15.gateway.ReplyRequest\x1a\x16.gateway.ReplyResponse\"\x00\x62\x06proto3')
)




_REPLYREQUEST = _descriptor.Descriptor(
  name='ReplyRequest',
  full_name='gateway.ReplyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='gateway.ReplyRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=53,
)


_REPLYRESPONSE = _descriptor.Descriptor(
  name='ReplyResponse',
  full_name='gateway.ReplyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='gateway.ReplyResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=87,
)


_INSPECTREQUEST = _descriptor.Descriptor(
  name='InspectRequest',
  full_name='gateway.InspectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='gateway.InspectRequest.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=118,
)


_INSPECTRESPONSE = _descriptor.Descriptor(
  name='InspectResponse',
  full_name='gateway.InspectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rss', full_name='gateway.InspectResponse.rss', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['ReplyRequest'] = _REPLYREQUEST
DESCRIPTOR.message_types_by_name['ReplyResponse'] = _REPLYRESPONSE
DESCRIPTOR.message_types_by_name['InspectRequest'] = _INSPECTREQUEST
DESCRIPTOR.message_types_by_name['InspectResponse'] = _INSPECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReplyRequest = _reflection.GeneratedProtocolMessageType('ReplyRequest', (_message.Message,), dict(
  DESCRIPTOR = _REPLYREQUEST,
  __module__ = 'rss_pb2'
  # @@protoc_insertion_point(class_scope:gateway.ReplyRequest)
  ))
_sym_db.RegisterMessage(ReplyRequest)

ReplyResponse = _reflection.GeneratedProtocolMessageType('ReplyResponse', (_message.Message,), dict(
  DESCRIPTOR = _REPLYRESPONSE,
  __module__ = 'rss_pb2'
  # @@protoc_insertion_point(class_scope:gateway.ReplyResponse)
  ))
_sym_db.RegisterMessage(ReplyResponse)

InspectRequest = _reflection.GeneratedProtocolMessageType('InspectRequest', (_message.Message,), dict(
  DESCRIPTOR = _INSPECTREQUEST,
  __module__ = 'rss_pb2'
  # @@protoc_insertion_point(class_scope:gateway.InspectRequest)
  ))
_sym_db.RegisterMessage(InspectRequest)

InspectResponse = _reflection.GeneratedProtocolMessageType('InspectResponse', (_message.Message,), dict(
  DESCRIPTOR = _INSPECTRESPONSE,
  __module__ = 'rss_pb2'
  # @@protoc_insertion_point(class_scope:gateway.InspectResponse)
  ))
_sym_db.RegisterMessage(InspectResponse)



_RSSSERVICE = _descriptor.ServiceDescriptor(
  name='RssService',
  full_name='gateway.RssService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=153,
  serialized_end=287,
  methods=[
  _descriptor.MethodDescriptor(
    name='Inspect',
    full_name='gateway.RssService.Inspect',
    index=0,
    containing_service=None,
    input_type=_INSPECTREQUEST,
    output_type=_INSPECTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Reply',
    full_name='gateway.RssService.Reply',
    index=1,
    containing_service=None,
    input_type=_REPLYREQUEST,
    output_type=_REPLYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RSSSERVICE)

DESCRIPTOR.services_by_name['RssService'] = _RSSSERVICE

# @@protoc_insertion_point(module_scope)
